# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "flexi_model"
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["nhm tanveer hossain khan"]
  s.date = "2012-07-10"
  s.description = "Flexible Model"
  s.email = ["hasan83bd@gmail.com"]
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "lib/discover.rb",
    "lib/flexi_model.rb",
    "lib/flexi_model/ar_models.rb",
    "lib/flexi_model/ar_models/collection.rb",
    "lib/flexi_model/ar_models/field.rb",
    "lib/flexi_model/ar_models/record.rb",
    "lib/flexi_model/ar_models/value.rb",
    "lib/flexi_model/ar_persistence.rb",
    "lib/flexi_model/ar_queryable.rb",
    "lib/flexi_model/association.rb",
    "lib/flexi_model/attachment_field.rb",
    "lib/flexi_model/callbacks.rb",
    "lib/flexi_model/fields.rb",
    "lib/flexi_model/filter.rb",
    "lib/flexi_model/stub_persistence.rb",
    "lib/flexi_model/validations.rb",
    "lib/generators/flexi_model/install/install_generator.rb",
    "lib/generators/flexi_model/install/templates/create_flexi_model_collections.rb",
    "lib/generators/flexi_model/install/templates/create_flexi_model_collections_fields.rb",
    "lib/generators/flexi_model/install/templates/create_flexi_model_fields.rb",
    "lib/generators/flexi_model/install/templates/create_flexi_model_records.rb",
    "lib/generators/flexi_model/install/templates/create_flexi_model_values.rb"
  ]
  s.homepage = "https://github.com/we4tech/flexi-model/"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Build flexible database model with dynamic fields (right now based on ActiveRecord soon it will work with mongoid too)"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, ["~> 3.2.6"])
      s.add_runtime_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<activesupport>, ["~> 3.2.6"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<activesupport>, ["~> 3.2.6"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

